FROM node:18-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git bash curl

COPY package*.json ./

RUN npm install

COPY . .

FROM node:18-alpine

LABEL maintainer="tu-email@dominio.com"
LABEL description="Backend Node.js app - Development"

WORKDIR /app

RUN npm install -g nodemon

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app ./

EXPOSE 3001 9229

ENV NODE_ENV=development

CMD ["npm", "run", "dev"]
